# Generated by Django 3.2 on 2021-08-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
