# Generated by Django 3.2 on 2021-08-15 10:45

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonoraryTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=500)),
                ('science', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=app_users.models.path_and_rename_teacher, verbose_name='Profile Picture')),
            ],
        ),
    ]
