# Generated by Django 3.2 on 2021-08-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_honoraryteachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honoraryteachers',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
