# Generated by Django 3.2 on 2021-08-15 09:52

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to=curriculum.models.save_course_image, verbose_name='Course Image')),
            ],
        ),
    ]
