# Generated by Django 3.2 on 2023-05-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20230523_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
